version: '3.1'

services:
  postgres:
    image: postgres
    container_name: "postgres"
    restart: always
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: deewave
      PGDATA: /var/postgres_data
    volumes:
      - postgres_data:/var/postgres_data
    ports:
      - "5432:5432"

  postgres_test:
    image: postgres
    container_name: "postgres_test"
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    restart: always

  redis:
    image: redis
    container_name: "redis"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  redis_test:
    image: redis
    container_name: "redis_test"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6378:6379"

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/mongodb/data/db
      - MONGO_LOG_DIR=/mongodb/dev/null
      - MONGODB_USER="user"
      - MONGODB_PASS="pass"
    volumes:
      - ./mongodb/data/db:/data/db
    ports:
      - 27017:27017

volumes:
  postgres_data: