version: '3.7'

services:
  app:
    container_name: "app"
    build: ./app/
    depends_on:
      - postgres
      - redis
      - rabbit
    networks:
      - network
    volumes:
      - .:/app
    ports:
      - "8080:8080" # REST API
      - "8081:8081" # сервис по заполнению кэша и поиску событий
      - "8082:8082" # вебсокеты

  postgres:
    image: postgres
    container_name: "postgres"
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: deewave
      PGDATA: /var/postgres_data
    volumes:
      - postgres_data:/var/postgres_data
    ports:
      - "5432:5432"
    networks:
      - network

  redis:
    image: redis
    container_name: "redis"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - network

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  rabbit:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    container_name: "rabbit"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    networks:
      - network

volumes:
  postgres_data:
  mongodb_data_container:
  app:

networks:
  network:
    driver: bridge
