version: '3.7'

services:
  restapi:
    container_name: "restapi"
    restart: always
    build: ./restapi/
    depends_on:
      - postgres
      - redis
      - rabbit
    volumes:
      - .:/restapi
    ports:
      - "8080:8080"

  events_cache:
    container_name: "events_cache"
    restart: always
    build: ./events_cache/
    depends_on:
      - postgres
      - redis
      - rabbit
    volumes:
      - .:/events_cache
    ports:
      - "8081:8081"

  consumer_events_main:
    container_name: "consumer_events_main"
    restart: always
    build: ./consumer_events_main/
    depends_on:
      - postgres
      - redis
      - rabbit
      - events_cache
    volumes:
      - .:/consumer_events_main

  consumer_events_user:
    container_name: "consumer_events_user"
    restart: always
    build: ./consumer_events_user/
    depends_on:
      - postgres
      - redis
      - rabbit
      - events_cache
    volumes:
      - .:/consumer_events_user

  ws_events:
    container_name: "ws_events"
    restart: always
    build: ./ws_events/
    depends_on:
      - postgres
      - redis
      - rabbit
    volumes:
      - .:/ws_events
    ports:
      - "8082:8082"

  postgres:
    image: postgres
    container_name: "postgres"
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: deewave
      PGDATA: /var/postgres_data
    volumes:
      - postgres_data:/var/postgres_data
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: "redis"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  rabbit:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    container_name: "rabbit"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"

volumes:
  postgres_data:
  mongodb_data_container:
  restapi: