version: '3.7'

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: "postgres"
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      PGDATA: /var/potstgres/postgres_data
    volumes:
      - .:/var/potstgres/
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: "redis"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  rabbit:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    container_name: "rabbit"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"

  jaeger:
    image: jaegertracing/all-in-one:1.45
    environment:
      COLLECTOR_OTLP_ENABLED: true
      SPAN_STORAGE_TYPE: badger
      BADGER_EPHEMERAL: false
      BADGER_DIRECTORY_VALUE: /badger/data
      BADGER_DIRECTORY_KEY: /badger/key
    volumes:
      - ./badger:/badger
    ports:
      - "16686:16686"
      - "4317:4317"

#  events:
#    container_name: events_service
#    image: vladimirylmv/events:latest
#    restart: always
#    volumes:
#      - ./events/logs:/app/logs
#      - ./events/config:/app/config
#    env_file:
#      - .env
#    ports:
#      - 8080:8080
#    depends_on:
#      - postgres
#      - redis
#      - rabbit

volumes:
  postgres_data:
