host: "127.0.0.1"
db_host: "172.17.0.1"
db_name: "deewave"
db_user: "user"
db_password: "qwerty"
db_port: "5434"
smtp_server: "smtp.yandex.ru"
email_user: "no-reply@deewave.online"
email_password: "moren5S5"
redis_host: "172.17.0.1:6377"