host: "172.17.0.1"
db_host: "172.17.0.1"
db_name: "deewave"
db_user: "user"
db_password: "qwerty"
db_port: "5432"
smtp_server: "mail.hosting.reg.ru"
email_user: "no-reply@porebric.ru"
email_password: "moren5S5"
redis_host: "172.17.0.1:6379"
rabbit_host_port: "172.17.0.1:5672"
rabbit_user: "guest"
rabbit_pass: "guest"
grpc_socket: "172.17.0.1:8081"